### ISSUE TITLE
Backport some fixes to 1.20.1

### ISSUE THREAD

**Issue by 3gf8jv4dv** [DevBobcorn/AcryliCraft#14]
Do you have any plans to backport some bug fixes to 1.20.1?

Based on Mojang’s current version control policy, 1.20.1 is still supported by many mod developers. Some other AcryliCraft corresponding game versions you have released (such as 1.19.4, 1.20.2~1.20.6) are transitional versions and do not require continued support. It would be a good idea if some important fixes could be ported to 1.20.1.

I have picked out some fixes from the commit history that I personally think need to be ported.

- https://github.com/DevBobcorn/AcryliCraft/commit/d527d9f6162469e075878c5263f60dd3c5f0bb03
Considering that many people use Sodium/Embeddium on Fabric and then use it with Sodium Extra.
- https://github.com/DevBobcorn/AcryliCraft/commit/6ef78b2aa0dd52f00d95efed980c240219f5618b
I am not quite sure what this commit actually does, because from the diff it only adds a line of comments.
- https://github.com/DevBobcorn/AcryliCraft/commit/ec237992ce66f2fef72f73ce01ad29d0b6c24372
This is relatively unimportant, since many people will only read the README of the default branch.
- https://github.com/DevBobcorn/AcryliCraft/commit/87c2f44ecb8e3516f89e8a10aed232ae8fd85a18
Take care of users of other OS.
- https://github.com/DevBobcorn/AcryliCraft/commit/93869f523c78e36c5c32ba76615123d905d2a45e
**HIGHLY RECOMMENDED:** This can serve as a good reminder and can also resolve some embarrassing moments. This prevents me from submitting false positives like #10 again.

**Comment by DevBobcorn** [comment]
So I've been looking into them for a while, and most of these bugfixes and features should have no problem making their way to 1.20.1, with the exception of https://github.com/DevBobcorn/AcryliCraft/commit/d527d9f6162469e075878c5263f60dd3c5f0bb03, which is not applicable to Forge/NeoForge 1.20.1 because constructor injectors are limited to `TAIL` injection points in old Forge(NeoForge 1.20.1 is basically still Forge, hence similar behavior), preventing the patch to be applied. However, I managed to fix this issue for Fabric 1.20.1, and since Sodium Extra is for Fabric only I guess it won't be a big problem.
