### ISSUE TITLE
Questions when the window material is `Auto`

### ISSUE THREAD

**Issue by 3gf8jv4dv** [DevBobcorn/AcryliCraft#19]
*The following description is based on Windows 22621 and above builds.*

I noticed that when the window material is set to `Auto`, the title bar of the game window is the Mica material, while the rest of the window is transparent. According to my personal understanding, if it is `Auto`, the expected behavior should be that the entire window is Mica material.

I am not sure if this is intended behavior, so I opened this issue.

**Comment by DevBobcorn** [comment]
It's called `Auto` in Windows' DWM API, which means the background is determined by the OS automatically. Since I'm not sure about its exact behaviour, the original name `Auto` is used to avoid confusion. There're `Mica` and `MicaAlt` materials available for full screen Mica effects, so I don't think it's necessary to have another option for this.
